# Docker Compose Configuration for Node.js Development
# keywords: docker, node.js, development, npm, live reload
node:
  user: node
  image: node:lts
  volumes:
    - ./src:/app
  working_dir: /app
  command: bash -c "npm ci && npm run dev:watch"
