media: media
content:
  - name: til
    label: TIL
    type: collection
    path: TIL
    view:
      fields: [title, date]
    fields:
      - { name: title, label: Title, type: string }
      - { name: tags, label: Tags, type: string, list: true}
      - { name: date, label: Date, type: date }
      - { name: body, label: Body, type: rich-text }