media: media
content:
  - name: index
    label: Index
    icon: table-of-contents
    type: file
    path: README.md
    fields:
      - { name: body, label: Body, type: text }
  - name: til
    label: TIL
    icon: calendar-check-2
    type: collection
    path: TIL
    view:
      fields: [title, date]
    fields:
      - { name: title, label: Title, type: string }
      - { name: tags, label: Tags, type: string, list: true}
      - { name: date, label: Date, type: date }
      - { name: body, label: Body, type: rich-text }
  - name: articles
    label: Articles
    icon: newspaper
    type: collection
    path: articles
    fields:
      - { name: title, label: Title, type: string }
      - { name: tags, label: Tags, type: string, list: true}
      - { name: date, label: Date, type: date }
      - { name: body, label: Body, type: rich-text }